services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KAGGLE_USERNAME=${KAGGLE_USERNAME}
        - KAGGLE_KEY=${KAGGLE_KEY}
    env_file: .env
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro  # Corrige timezone no container
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
